apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nodeapp
        image: chymaslik/node:test
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
